### ISSUE TITLE
Pip install command doesn't work

### ISSUE THREAD

**Issue by arielfeldman** [nipy/napari-nibabel#2]
When using the pip command located in the README file in Python (I'm using Python 3.7.1), I receive an error saying the following:

ERROR: Could not find a version that satisfies the requirement napari-nibabel (from versions: none)
ERROR: No matching distribution found for napari-nibabel

**Comment by effigies** [comment]
It looks like it was not uploaded to PyPI. You should be able to install with `pip install git+https://github.com/nipy/napari-nibabel.git`

**Comment by arielfeldman** [comment]
That works! Thanks :)
