### ISSUE TITLE
Package structure

### ISSUE THREAD

**Issue by Chris-N-K** [nipy/napari-nibabel#4]
Hi,

I would like to discuss the structure of the package. Wouldn't it be good to split the scripts into a _reader.py and _writer.py file in the future? Possily a _widget.py or _header_info.py as well? I used this structure in my approach and I think it might be beneficial.

Best regards,
Christopher

**Comment by Chris-N-K** [comment]
@grlee77 what's your oppinion?

**Comment by grlee77** [comment]
Yes, that sounds reasonable to me.

**Comment by Chris-N-K** [comment]
Ok, I will include the new structure in my first development branch then.
